#pragma once

static constexpr int BOARD_WIDTH = 8;
static constexpr int BOARD_HEIGHT = 8;

static constexpr const char
*BOARD_CORNER_TOP_RIGHT = u8"╗",
*BOARD_CORNER_TOP_LEFT = u8"╔",
*BOARD_CORNER_BOTTOM_RIGHT = u8"╝",
*BOARD_CORNER_BOTTOM_LEFT = u8"╚",
*BOARD_EDGE_HORIZONTAL = u8"═══",
*BOARD_EDGE_VERTICAL = u8"║",
*BOARD_EDGE_VERTICAL_LEFT = u8"╟",
*BOARD_EDGE_VERTICAL_RIGHT = u8"╢",
*BOARD_EDGE_HORIZONTAL_BOTTOM = u8"╧",
*BOARD_EDGE_HORIZONTAL_TOP = u8"╤",
*BOARD_INTERNAL_HORIZONTAL = u8"───",
*BOARD_INTERNAL_VERTICAL = u8"│",
*BOARD_INTERNAL_INTERSECT = u8"┼",

*RED = "\u001b[31;1m",
*RED_HIGHLIHT = "\u001b[41;1m",
*BRIGHT_RED = "\u001b[91;1m",
*BRIGHT_RED_HIGHLIHT = "\u001b[101;1m",
*GREEN = "\u001b[32;1m",
*BRIGHT_YELLOW = "\u001b[93;1m",
*BRIGHT_BLUE = "\u001b[96;1m",
*BRIGHT_GREEN_HIGHLIGHT = "\u001b[45;1m",
*RESET = "\u001b[0m"
;